# Change these first
owner: memoteki # Your GitHub username
repo: stats # Your Github repository name

# Add your sites here
sites:
  - name: memoteki.net
    url: https://memoteki.net
  - name: file.memoteki.net
    url: https://file.memoteki.net

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: stats.memoteki.net
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Memoteki Status"
  introMessage: This is the status page for memoteki.net websites, powered entirely by GitHub.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Blog
      href: https://memoteki.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
